### PR TITLE
MGMT-11036: Update API for upgrade agent feature

### PR DESCRIPTION
**Pull request by jhernand**
https://issues.redhat.com/browse/MGMT-11036

This patch updates the OpenAPI specification and the code generated from
it, so that it will be possible to use the new `compatible-agent`
validation.

### CODE REVIEW

**Comment by jkilzi** [comment]
This PR requires https://github.com/openshift/assisted-service/pull/3942 to be merged first

**Comment by jkilzi** [comment]
@jhernand please in the future, we'll greatly appreciate if you could add a link in the JIRA ticket to the PR and vice-versa.
This kind of automation is not yet available to us in this GH org. :(

**Comment by jkilzi** [comment]
@ammont82 PTAL

**Review by ammont82 — APPROVED** [review]

**Comment by jkilzi** [comment]
@jhernand @gamli75 for what BE version is this change scheduled?
I'm asking because I'm about to prepare a release of v2.6. Is this meant to be part of this version in the BE too?

**Review by jkilzi — APPROVED** [review]

**Pull request merged**
