### PR TITLE
BZ-1975228: CNV help popover arrow is misplaced

### PR DESCRIPTION
**Pull request by jkilzi**
[BZ-1975228](https://bugzilla.redhat.com/show_bug.cgi?id=1975228)

Before:
https://user-images.githubusercontent.com/77008341/125964772-b639dad7-4c5d-4730-9249-651ac8e300ce.mp4

After:
https://user-images.githubusercontent.com/77008341/125964506-03e57eb8-6121-46bc-bc8c-aa8e8eaeb209.mp4

### CODE REVIEW

**Comment by nirfarkas** [comment]
@jkilzi Don't operators have a step of their own?
The "?" is a bit off position (up a few pixels)

**Comment by jkilzi** [comment]
> Don't operators have a step of their own?
No, they don't have their own step, although this topic has been discussed many times, we currently don't have a task for presenting them in a dedicated "operators step"

> The "?" is a bit off position (up a few pixels)
That's because the symbol has changed in order to align with the one you used in the mock, the gray/black I mean.

**Comment by nirfarkas** [comment]
> No, they don't have their own step, although this topic has been discussed many times, we currently don't have a task for presenting them in a dedicated "operators step".

We don't want to or we don't have the capacity?

> That's because the symbol has changed in order to align with the one you used in the mock, the gray/black I mean.

So, can we align it to the text?

**Comment by jkilzi** [comment]
> We don't want to or we don't have the capacity?

I believe we do want this... we need to discuss it further

> So, can we align it to the text?

on it ... :)

**Review by rawagner — APPROVED** [review]

**Pull request merged**
