### PR TITLE
MGMT-10185: UI not blocking "localhost" name changing

### PR DESCRIPTION
**Pull request by jgyselov**
https://issues.redhat.com/browse/MGMT-10185

I also specified that characters need to be lowercase, since uppercase letters are not allowed.

Before:
image

After:
image

### CODE REVIEW

**Comment by rawagner** [comment]
@jgyselov you sure about the lowercase requirement ? I think when we tried it, it worked fine IIRC

**Comment by rawagner** [comment]
I think the DNS resolution is case insensitive

**Comment by jgyselov** [comment]
Maybe it's a new BE requirement? It definitely doesn't let me put uppercase characters in the hostname. @rawagner 
image

**Comment by rawagner** [comment]
you're right. I just checked on k8s API and it is the same.

**Comment by celdrake** [comment]
@jgyselov Does it only affect the hosts being renamed? Or I three hosts are discovered with `localhost` name, would it be a problem?

**Comment by jgyselov** [comment]
> Does it only affect the hosts being renamed? Or I three hosts are discovered with `localhost` name, would it be a problem?

No host can be named `localhost`. If it is, it's automatically `insufficient` and the cluster cannot be installed until those hosts are renamed. @celdrake

**Comment by celdrake** [comment]
> 

What I mean is that when you are renaming 1 host, the other 2 will still have the invalid name "localhost". 
Just to confirm, that the validation does not block renaming the hosts individually etc.

**Comment by jgyselov** [comment]
> What I mean is that when you are renaming 1 host, the other 2 will still have the invalid name "localhost". Just to confirm, that the validation does not block renaming the hosts individually etc.

I don't think I specifically tried this scenario where all host are name `localhost` at the beginning. But the validations are always just checking the potential new name against these conditions so it shouldn't block anything.

**Review by jkilzi — APPROVED** [review]

**Review by jkilzi — APPROVED** [review]

**Pull request merged**
