### PR TITLE
MGMT-7527: Deprecate old cluster networking fields in the UI

### PR DESCRIPTION
**Pull request by jgyselov**
https://issues.redhat.com/browse/MGMT-7527

### CODE REVIEW

**Comment by jgyselov** [comment]
```
export const selectMachineNetworkCIDR = ({
  machineNetworks,
  machineNetworkCidr,
}: Partial<Cluster>) => head(machineNetworks)?.cidr ?? machineNetworkCidr;
export const selectClusterNetworkCIDR = ({
  clusterNetworks,
  clusterNetworkCidr,
}: Partial<Cluster>) => head(clusterNetworks)?.cidr ?? clusterNetworkCidr;
export const selectClusterNetworkHostPrefix = ({
  clusterNetworks,
  clusterNetworkHostPrefix,
}: Partial<Cluster>) => head(clusterNetworks)?.hostPrefix ?? clusterNetworkHostPrefix;
export const selectServiceNetworkCIDR = ({
  serviceNetworks,
  serviceNetworkCidr,
}: Partial<Cluster>) => head(serviceNetworks)?.cidr ?? serviceNetworkCidr;
```
Throughout the code we use these functions from [clusterSelectors.ts](https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/common/selectors/clusterSelectors.ts#L8-L23) in /common. Can we keep using these functions and rely on the BE always sending the `machineNetworks`, `serviceNetworks`, and `clusterNetworks` arrays correctly or would creating new functions in /ocm be a better approach?

**Comment by jkilzi** [comment]
> ```
> export const selectMachineNetworkCIDR = ({
>   machineNetworks,
>   machineNetworkCidr,
> }: Partial<Cluster>) => head(machineNetworks)?.cidr ?? machineNetworkCidr;
> export const selectClusterNetworkCIDR = ({
>   clusterNetworks,
>   clusterNetworkCidr,
> }: Partial<Cluster>) => head(clusterNetworks)?.cidr ?? clusterNetworkCidr;
> export const selectClusterNetworkHostPrefix = ({
>   clusterNetworks,
>   clusterNetworkHostPrefix,
> }: Partial<Cluster>) => head(clusterNetworks)?.hostPrefix ?? clusterNetworkHostPrefix;
> export const selectServiceNetworkCIDR = ({
>   serviceNetworks,
>   serviceNetworkCidr,
> }: Partial<Cluster>) => head(serviceNetworks)?.cidr ?? serviceNetworkCidr;
> ```
> 
> Throughout the code we use these functions from [clusterSelectors.ts](https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/common/selectors/clusterSelectors.ts#L8-L23) in /common. Can we keep using these functions and rely on the BE always sending the `machineNetworks`, `serviceNetworks`, and `clusterNetworks` arrays correctly or would creating new functions in /ocm be a better approach?

@osherdp?

**Comment by jkilzi** [comment]
@jgyselov Let's merge this PR, since the default place we use for looking up for the *NetworkCidrs is in the new fields.
We can open an independent RFE later to completely remove the old fields.

**Review by jkilzi — APPROVED** [review]

**Comment by mkowalski** [comment]
Folks, be aware, `*NetworkCidr` fields are now **empty**. They may be returned in the payload, but you must never ever rely on their values. `*Networks` are the only ones to be used in both GET and POST.

POST action against `*NetworkCidr` will not cause any change to the Cluster object.
GET action against `*NetworkCidr` will return an empty value even if the respective `*Networks` contains a proper value.

**Comment by jkilzi** [comment]
Yes Mat you're right, I meant the *Network fields. I've edited my previous comment. Thanks for pointing that out.

**Pull request merged**
