### PR TITLE
Bug 2056485: Add pagination to tables if there are more than 10 items

### PR DESCRIPTION
**Pull request by rawagner**
Screenshot from 2022-02-25 11-15-18

@nirfarkas this adds pagination for every AI table in ACM and OCM when we have more than 10 items to show

### CODE REVIEW

**Review by mareklibra — DISMISSED** [review]

**Comment by nirfarkas** [comment]
Looks great!

**Comment by rawagner** [comment]
PR updated, the pagination is not added to the top right corner too, if the table has a toolbar

Screenshot from 2022-03-01 15-27-12

Screenshot from 2022-03-01 15-27-28

**Comment by nirfarkas** [comment]
You have my blessing (: 
Looking great!

**Review by jtomasek — APPROVED** [review]

**Pull request merged**
