### PR TITLE
MGMT-12704 - Show "soft-validations" as info-alerts instead of warnings

### PR DESCRIPTION
**Pull request by jgyselov**
https://issues.redhat.com/browse/MGMT-12704

The "NTP synchronization failure" (and other possible future non-blocking soft validations) will be shown in blue.

image

### CODE REVIEW

**Comment by nirfarkas** [comment]
Let's remove the "please".
"Host couldn't synchronize with any NTP server. Fix manually host's NTP configuration or provide additional
NTP sources."
@allison WDYT?

**Comment by wolfeallison** [comment]
"Host couldn't synchronize with any NTP server. Manually fix the host's NTP configuration or provide additional
NTP sources."  @nirfarkas Slight change to make it a little more easy to read

**Comment by nirfarkas** [comment]
Perfect!

**Comment by jgyselov** [comment]
Changed.

image

**Review by ammont82 — APPROVED** [review]

**Review by celdrake — APPROVED** [review]

**Pull request merged**
