### PR TITLE
Sync API types with UI's

### PR DESCRIPTION
**Pull request by celdrake**
Run `update_api` to synchonize API and UI definitions

**Relevant changes that may need changes:**

- `ovirt_platform` has been deleted (however `platform.type` still allows the value `ovirt`, should it have been removed too?=

- New host statuses: `reclaiming`, `reclaiming-rebooting`. These probably need to be mapped in the UI?
eg https://github.com/openshift-assisted/assisted-ui-lib/blob/master/src/common/components/hosts/status.tsx#L24

**Changes that should not require UI chaanges**

- New `FeatureSupportLevel` values for `LVM`, `DUAL_STACK_NETWORKING`, `MULTIARCH_RELEASE_IMAGE`

- Disk holders information added (will be implemented soon)

- Deprecated `cpuArchitecture` in favor of  `cpuArchitectures` but UI will use the old field for now.

### CODE REVIEW

**Review by batzionb — APPROVED** [review]

**Review by jkilzi — APPROVED** [review]

**Comment by jkilzi** [comment]
> ovirt_platform has been deleted (however platform.type still allows the value ovirt, should it have been removed too? 

@osherdp FYI ^ (Celia's question in the description)

**Comment by jkilzi** [comment]
> ovirt_platform has been deleted (however platform.type still allows the value ovirt, should it have been removed too? 

@osherdp FYI ^ (Celia's question in the description)

**Comment by osherdp** [comment]
> > ovirt_platform has been deleted (however platform.type still allows the value ovirt, should it have been removed too?
> 
> @osherdp FYI ^ (Celia's question in the description)

@eliorerz did we just forgot to remove this value?

**Comment by eliorerz** [comment]
Basically we still can set `ovirt` as a platform on assisted-service. We removed the object that defines `ovirt` extra parameters.

**Pull request merged**
