### PR TITLE
MGMT-6009: Rephrase Additional requirements for CNV

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by mareklibra** [comment]
Cc @nirfarkas

**Review by jtomasek — CHANGES_REQUESTED** [review]
IMHO the renaming should go hand in hand with the backend + other UI parts to avoid having "master" and "supervisor" used at the same time which will be very confusing.

**Comment by nirfarkas** [comment]
So I guess we should have the UI & BE change every "Master" to "Supervisor"

**Comment by mareklibra** [comment]
Filing MGMT-6009, let's discuss the issue there first.

**Comment by jkilzi** [comment]
Closing this since it has been implemented in v1.5.28 already as part of [MGMT-5284](https://issues.redhat.com/browse/MGMT-5284)

**Pull request closed without merging**
