### PR TITLE
MGMT-8342 : Update approval popover

### PR DESCRIPTION
**Pull request by rawagner**
Screenshot from 2022-02-02 12-46-43

@ShiranHi Can you take a look ?
I dropped the MAC address field as we dropped it in mass approve modal too.

### CODE REVIEW

**Comment by ShiranHi** [comment]
@rawagner the text is geat, @nirfarkas please let us know if you have any input on this. 
Re. the popover: can we make it not that wide, I think it is too hard to read such a long text line, wdyt? 
Could be like this: https://marvelapp.com/prototype/haechg7/screen/83677573

**Comment by rawagner** [comment]
@ShiranHi updated. Im not sure if we want to put the `approving.` on another line ? Seems bit unnecessary to me.

**Comment by ShiranHi** [comment]
@rawagner looks good to me

**Comment by nirfarkas** [comment]
Why do we need the host name in the popover?

**Comment by nirfarkas** [comment]
FYI Allison

**Comment by rawagner** [comment]
> Why do we need the host name in the popover?

not sure, i would prefer to drop it

**Comment by ShiranHi** [comment]
> > Why do we need the host name in the popover?

To make sure the users understand that popover is about this host, and also sometimes the hostname has changed (and then we show the original one)

**Comment by wolfeallison** [comment]
Hi! It feels pretty repetitive in the header and the first sentence of the body. What do you think of removing the first sentence? So it would be: 
"**Approve host to add it to the infrastructure.** 

Make sure that you expect and recognize the host before approving. 
hostname: localhost

Approve host"

**Comment by rawagner** [comment]
> > > Why do we need the host name in the popover?
> 
> To make sure the users understand that popover is about this host, and also sometimes the hostname has changed (and then we show the original one)

uh, i dont do that right now. The hostname that is shown in popup is the changed one. Do we really want to show original ? wouldnt that be confusing ? What if somebody else changed the hostname and now Im deleting..suddenly the hostname is different than the one shown in the table

**Comment by ShiranHi** [comment]
@rawagner I am sorry it was not clear, maybe it should be "Original hostname"? and maybe it should appear only when the name has changed?

**Review by jtomasek — APPROVED** [review]

**Comment by rawagner** [comment]
/hold

needs some more discussion with UXD

**Comment by mareklibra** [comment]
Reverting.
@rawagner please file a new PR if you want this or an update in master. I am sorry for the mess, too late notice.

**Pull request merged**
