### PR TITLE
Use github prism theme as default

### PR DESCRIPTION
**Pull request by mareklibra**
Follow-up for #396.

### CODE REVIEW

**Comment by mareklibra** [comment]
Former state:



---

**Comment by mareklibra** [comment]
From the discussed options I like using of the PrismCode but with different theme at most:



---

**Comment by mareklibra** [comment]
Cc @andybraren , @nirfarkas , @jtomasek

**Review by jtomasek — APPROVED** [review]

**Comment by nirfarkas** [comment]
Looking Great!

**Pull request merged**
